### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/organization#1]
we need a cool logo

**Comment by kumavis** [comment]
I'm not a huge fan but this is a theme in the js community:
![image](https://cloud.githubusercontent.com/assets/1474978/11798765/92809ae6-a282-11e5-8a48-b608f4154d26.png)
theres also node.js style hexagons
![image](https://cloud.githubusercontent.com/assets/1474978/11798779/ce31f21a-a282-11e5-86fc-302d515d9f19.png)
which have their own following that expands beyond js
http://hexb.in/
![image](https://cloud.githubusercontent.com/assets/1474978/11798785/eb57ddf0-a282-11e5-93fd-68a8e9e3f694.png)

**Comment by wanderer** [comment]
I think we should start with Ethereum's tetrahedron https://www.ethereum.org/images/logos/Ethereum_Visual_Identity_1.0.0.pdf then somehow work in JS

**Comment by kumavis** [comment]
agree. javascript is definitely lacking in ready-to-use visual cues

**Comment by cassiopaia** [comment]
Let me try if i can be of assistance here! I will try to send some ideas for a potential logo …

**Comment by hitchcott** [comment]
cross-reffing logo.js repo for ideas

https://github.com/voodootikigod/logo.js

Also gonna have a shot at this ;)

**Comment by hitchcott** [comment]
A few obvious ideas to kick things off:

![initial ethereum js logo ideas](https://sli.mg/lofl3c.png)

I think the black and yellow is actually quite nice.

**Comment by cassiopaia** [comment]
![eth-js](https://cloud.githubusercontent.com/assets/6280810/11849083/4b779848-a426-11e5-99f3-a0bde37d0324.png)

**Comment by cassiopaia** [comment]
![eth-js](https://cloud.githubusercontent.com/assets/6280810/11849127/81fb6aca-a426-11e5-94dc-0344f4139b34.png)

**Comment by kumavis** [comment]
@hitchcott @cassiopaia nice!

**Comment by cassiopaia** [comment]
i will try to provide another draft later this week .. have to priorize some other tasks before..

**Comment by axic** [comment]
@hitchcott love the bottom row!

**Comment by kumavis** [comment]
bottom middle is works for me, also happy to see more iterations

**Comment by wanderer** [comment]
![ethcube](https://cloud.githubusercontent.com/assets/158211/11890156/3528c08e-a549-11e5-8200-4cb2247850b1.png)

**Comment by wanderer** [comment]
![ethjs](https://cloud.githubusercontent.com/assets/158211/11908259/894d4c64-a5d2-11e5-8f48-7df61dc7feaf.png)

**Comment by hitchcott** [comment]
A few more iterations, and playing on @wanderer's version:

![iterated ideas](https://i.sli.mg/AUMjtQ.png)

**Comment by hitchcott** [comment]
And this time in `#ECF0F1`, as per the brand guidelines; a bit cooler?

![cooler](https://i.sli.mg/DwYJxN.png)

**Comment by cassiopaia** [comment]
![eth-js-4](https://cloud.githubusercontent.com/assets/6280810/11916259/ee3342da-a6ce-11e5-9971-1c5a9d978d1b.png)

**Comment by cassiopaia** [comment]
![eth-js-8](https://cloud.githubusercontent.com/assets/6280810/11916310/ee1e460c-a6d1-11e5-8152-9dce0b788d03.png)

**Comment by wanderer** [comment]
@cassiopaia and @hitchcott very nice! @cassiopaia i really dig highlighting the `js`.  I think the third logo on your second post with the `ethereumjs` from your last is my favorite so far.

**Comment by zelig** [comment]
my 2c if I may: @cassiopaia's design is awesome orange js as face inside the ethereum logo as warrior helmet. (post 4 days ago) it is actually cool. the organic blend due to the geometric fit there would be a mistake to miss. the rest are a bit boring

**Comment by cassiopaia** [comment]
![eth-js-1](https://cloud.githubusercontent.com/assets/6280810/11920322/050715ac-a76c-11e5-8d71-f7dbc7d3a6f7.png)

**Comment by cassiopaia** [comment]
![eth-js-2](https://cloud.githubusercontent.com/assets/6280810/11920323/14b33a8a-a76c-11e5-889f-7632ddc2c730.png)

**Comment by cassiopaia** [comment]
![eth-js-22](https://cloud.githubusercontent.com/assets/6280810/11921456/6ce755d4-a789-11e5-9986-8137ce7c9d70.png)

played with another idea ..(more for fun tbh :dash: )

**Comment by juanfranblanco** [comment]
first one, very nice, second a bit busy, colours are great.

**Comment by cassiopaia** [comment]
![eth-js-22 1](https://cloud.githubusercontent.com/assets/6280810/11934117/522dcae4-a800-11e5-9d6d-18f49288776b.png)

**Comment by kumavis** [comment]
i think this one is my fav so far https://github.com/ethereumjs/organization/issues/1#issuecomment-166059742

**Comment by kumavis** [comment]
Who did this one?
![image](https://cloud.githubusercontent.com/assets/1474978/11941398/1f7e8bc2-a7e4-11e5-9d1b-82a9bfd09bb7.png)

**Comment by wanderer** [comment]
I think @tinybike. I have heard a lot of good feedback on https://github.com/ethereumjs/organization/issues/1#issuecomment-166059742

**Comment by kumavis** [comment]
@cassiopaia can you provide https://github.com/ethereumjs/organization/issues/1#issuecomment-166059742 with a white / transparent background and close crop

thanks!

**Comment by cassiopaia** [comment]
ok .. you'll need it for github here? ..400x400px ..

**Comment by wanderer** [comment]
@cassiopaia yep 400x400 would be great!

**Comment by cassiopaia** [comment]
https://github.com/cassiopaia/ethJS-ci/tree/master/ethJS_logo/github-icon

https://github.com/cassiopaia/ethJS-ci/blob/master/ethJS_logo/github-icon/ethJS-git-logo-icon.png

**Comment by tinybike** [comment]
@kumavis I did that one

**Comment by hitchcott** [comment]
@cassiopaia I also agree that https://github.com/ethereumjs/organization/issues/1#issuecomment-166475933 is the best one so far -- but I'd like to see an iteration without the drop shadow and using the original 'JS' font

**Comment by cassiopaia** [comment]
@hitchcott: thanks for your comment. For the font .. i would advise to go with ETH CI font ( Roboto ) as this is the general used font .. 

Sry no PSD/AI files ... working with sketch

**Comment by cassiopaia** [comment]
i will convert it later on .. @hitchcott

**Comment by kumavis** [comment]
Doing some spring cleaning -- thanks all for contributing here!

**Comment by cassiopaia** [comment]
happy to help

**Comment by hitchcott** [comment]
Good times! :)
