### ISSUE TITLE
Move issues from the ideas repo to here

### ISSUE THREAD

**Issue by axic** [ethereumjs/organization#10]
Can use this tool: https://github.com/google/github-issue-mover

**Comment by holgerd77** [comment]
https://github.com/ethereumjs/ideas/issues

In the follow-up, ``ideas`` repository should be deprecated and archived (or maybe just deleted (?)).

**Comment by holgerd77** [comment]
Did the transfer, deleted ``ideas`` repository, wasn't worth to keep or archive.

**Comment by axic** [comment]
> Did the transfer, deleted ideas repository, wasn't worth to keep or archive.

Did you use the new "transfer issue" feature from github?

**Comment by axic** [comment]
Great!
