### ISSUE TITLE
Requiring 2FA for the ethereumjs org

### ISSUE THREAD

**Issue by axic** [ethereumjs/organization#11]
I'd like to turn requiring 2FA on.

Out of 22 people only 4 do not have 2FA set up: @aakilfernandes, @epheph, @iurimatias and @MicahZoltu

Let's set a deadline 2 weeks from now: 14th February

Please set up 2FA, otherwise on that date Github will remove you from the org, though I am happy to add back anyone after they've set up 2FA.

**Comment by holgerd77** [comment]
I would also urge everyone to activate 2FA for npm publishing (this is also a note to self).

**Comment by axic** [comment]
Guide for npm: https://docs.npmjs.com/getting-started/using-two-factor-authentication

**Comment by epheph** [comment]
Enabled 2FA

**Comment by iurimatias** [comment]
Enabled 2FA as well.

**Comment by MicahZoltu** [comment]
Done, begrudgingly.

**Comment by SilentCicero** [comment]
Two factor or nothing... and yay security!

**Comment by holgerd77** [comment]
Enabled 2FA for npm as well and did a first release with this. Easier/more comfortable then I would have thought on the CL. Just make sure that your ``npm`` version meets the min version requirements (see guide mentioned above), since this is pretty new stuff only available in the latest releases.

**Comment by axic** [comment]
> but does increase login complexity.

@MicahZoltu it doesn't require 2FA to log in if you have a local cookie (for the better or the worse), but does on a new set up. 

@aakilfernandes tomorrow's the deadline

**Comment by axic** [comment]
2FA is turned on now.
