### ISSUE TITLE
Push a new commit on deprecated repos replacing the README

### ISSUE THREAD

**Issue by axic** [ethereumjs/organization#13]
The `README` should point the user to the location of the successor project. Also preferably every other file should be removed only leaving the `README` (Git history can still be used to find everything else if needed).

Affected:
- [x] https://github.com/ethereumjs/ethereumjs-lib
- [x] https://github.com/ethereumjs/node-devp2p-rlpx
- [x] https://github.com/ethereumjs/node-devp2p-eth
- [x] https://github.com/ethereumjs/node-devp2p-dpt
- [x] https://github.com/ethereumjs/node-devp2p
- [x] https://github.com/ethereumjs/node-blockchain-server

**Comment by holgerd77** [comment]
@axic Repository have all been archived and set to read-only, did you do this? Should I de-archive and do these changes and re-archive or leave it for now?

**Comment by axic** [comment]
@holgerd77 yep. Please do as you've described :)

**Comment by holgerd77** [comment]
What do you think alternatively about an additional organization ``ethereumjs-attic`` where we move stuff like this? Then this is archived + out of the way and doesn't always get into sight/distract from the active repositories when scrolling through the repository list?

**Comment by holgerd77** [comment]
Ok, don't want to push on this any further. I will then just go on with the initial suggestion.
