### ISSUE TITLE
Migrate wiki on ethereumjs-lib repo to elsewhere

### ISSUE THREAD

**Issue by axic** [ethereumjs/organization#14]
See https://github.com/ethereumjs/ethereumjs-lib/wiki/Architecture

**Comment by holgerd77** [comment]
Oh, never saw this. Interesting!

**Comment by holgerd77** [comment]
Just had a closer look here, definitely makes no sense any more to move over all of the information (outdated). Explanations are nevertheless well written and describe architectural thoughts on a very basic level. It might be worth to have some closer look and move over some extracts.

First look suggestion:

- Give it a proof read and move over the [MPT checkpointing part](https://github.com/ethereumjs/ethereumjs-lib/wiki/Architecture#merkle-patricia-trie-checkpointing) to the [MPT](https://github.com/ethereumjs/merkle-patricia-tree) README
- Have a look at the [State Overview](https://github.com/ethereumjs/ethereumjs-lib/wiki/Architecture#updating-the-state-overview) section and see if this can serve as some inspiration to improve the [Internal Structure](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/vm#internal-structure) section of the VM README, have the first impression that the architectural description from here covers the VM functionality in a more holistic way compared to what is written down in the README

Feel free to give this a second read and conclude that it is not worth it though.
