### ISSUE TITLE
Rename main Gitter communcation channel from ethereumjs-lib to ethereumjs

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/organization#15]
The Gitter channel used for ``ethereumjs`` communication at gitter.im/ethereum/ethereumjs-lib is still named after the old central VM library ``ethereumjs-lib``, which is now in a deprecated/archived state.

This is misleading for new users and also doesn't provide a clear scope of the topics discussed in the channel.

Channel should be renamed to just ``ethereumjs``, with a final "channel has moved" message on the old channel.

Over time links in the README pages of the various libraries should be updated as well.

**Comment by axic** [comment]
I think gitter.im support is able to rename the channel.

**Comment by jamesray1** [comment]
Agreed, I also thought it was odd.

**Comment by axic** [comment]
This has been done a while ago 😉
