### ISSUE TITLE
Project suggestion: create monorepo for blockchain data schemes

### ISSUE THREAD

**Issue by axic** [ethereumjs/organization#19]
- ethereumjs-tx
- ethereumjs-acocunt
- ethereumjs-block
- [ethereumjs-collation]

All of these provide (de)serialisation of data. They could be placed into a single repo, where the appropriate modules can still be loaded selectively from the outside, for example: `require('ethereumjs-data-schemes/tx`).

This should help in the maintenance work as it would reduce the number of repositories.

**Comment by holgerd77** [comment]
Closed by execution upon https://github.com/ethereumjs/ethereumjs-vm/issues/561
