### ISSUE TITLE
Coveralls - Introduce decrease and absolute failure thresholds

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/organization#22]
Just discovered that Coveralls allows for both decrease and absolute thresholds (on the project settings page) for indicating failure on CI runs.

I've now set the descrease failure threshold to ``0.5%`` for the VM, since in practice many PRs are displayed as failure just because of tiny coverage decreases, which limits the meaningfulness of build overviews.

This should be done for the different libraries with a practical threshold. There probably should also be inserted an absolute threshold to encourage to stay above a desired limit.

**Comment by axic** [comment]
Good call, agreed.

**Comment by holgerd77** [comment]
Have done this over time for many/most of the libraries and will add if something is still missing, no need for a separate issue any more to track, will close.
