### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by hitchcott** [ethereumjs/organization#3]
Would it be possible to start up a gitter room for ethereumjs?

ie. https://gitter.im/ethereumjs

EDIT: Just noticed the link on the readme; should we be using https://gitter.im/ethereum/ethereumjs-lib for all repos ?

**Comment by wanderer** [comment]
So far the volume level has been low enough that I have just linked all repo to that one room. But if we get tons of traffic maybe it would be a good idea to break them up by repo.

**Comment by axic** [comment]
I think gitter.im/ethereumjs would be nicer - is there a way to rename the current channel? Starting a new with this level of traffic won't make any sense.

**Comment by kumavis** [comment]
i dont think so - maybe provide a link in the chats, with some markdown formatting, thats about it

**Comment by wanderer** [comment]
If there was a way to bridge the channel then I'm down.

**Comment by axic** [comment]
The way to do it by renaming the original repository it is tied to. Alternatively a support request can be submitted to Gitter to make it a channel not tied to a repo.
