### ISSUE TITLE
Educational visualization suite & framework

### ISSUE THREAD

**Issue by courajs** [ethereumjs/organization#30]
It would be awesome to have a scriptable visualization framework that could be used to explore properties of the network, or to create educational animations.

I'm pretty new to the crypto and ethereum space, and what would help a lot in my understanding is a set of animations of the execution of simple contract code, how a block is propagated and verified, and how the network rejects false blocks injected by a malicious actor would be AMAZING.

I'm imagining a bit of an in-browser emulater, where I could set up nodes, "deploy" contracts, step through the mining process, designate a node to find a block, essentially step through any part of the protocol on any node. Then, if this was scriptable, we could create a suite of explanatory animations for those looking for an accurate picture of how the network actually works.

**Comment by holgerd77** [comment]
Old issue and no follow-up (also not really a dedicated issue, rather an idea write-up). Will close here.
