### ISSUE TITLE
alternate ethereum front-end lib

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/organization#32]
ideals:
- single observable lazy state tree
- emit top-level events for block, fork
- subscribe to logs, account balance/nonce/storage, etc

account.balance -> value is pumped to somewhere in state trie
- set focus via blocks-from-head parameter

always query state 5-blocks back from head, tx not 'firm' until 5 blocks back from head
- pipelines > callbacks
- submit tx, get results
- submit tx suggestion, get back a generic filter that can handle stranger cases (e.g. look for log from completeion of on-chain multisig, meta-tx's)

``` js
var pendingTx = exampleContract.foo.sendTransaction(2, {from: web3.eth.coinbase});
// transaction hash
pendingTx.getHash(funtion(err, result){ console.log(result) }) // tx hash
pendingTx.on('returnValue', function(err, returnValue){ console.log(returnValue) }) // tx return value
```

**Comment by holgerd77** [comment]
Will close this on non-activity, feel free to reopen if you want to re-take on this.
