### ISSUE TITLE
Missing labels for new labelling system (round 2)

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/organization#41]
Some more collection on labels, since I stumbled upon one I would very much like to integrate. Will eventually do a third integration round within a couple of weeks.

**Comment by holgerd77** [comment]
An ``eval: needs analysis`` label would very much complement the current ``eval`` type labels.

Sometimes/often issues require a large amount of extra thought/analysis work before one can start to code. A dedicated label makes it more explicit that this is actually a significant separate work step  before coding (which can also very well be taken on by a different person). This should to some extend ease the path towards the final implementation.

**Comment by holgerd77** [comment]
Sometimes missing `effort: E0 minutes` and `effort: E5 years`

**Comment by ryanio** [comment]
Suggestion: `PR: breaking change`

**Comment by holgerd77** [comment]
Missing a `type: maintenance` label, example case: https://github.com/ethereumjs/ethereumjs-client/issues/149

**Comment by evertonfraga** [comment]
I have opened a PR with @holgerd77 's new type label.

@ryanio how about we use it like `type: breaking change`? Because it doesn't quite fit on the PR states category.
