### ISSUE TITLE
ethereum js call

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/organization#5]
time: January 5th, Thursday 2pm EST
link: https://plus.google.com/hangouts/_/calendar/dGhlbmlja2RvZHNvbkBnbWFpbC5jb20.m37a8o7jhikbar1jp303neqcl0?authuser=0

@kumavis  @axic @SilentCicero

Time and Date work for everyone?

**Comment by kumavis** [comment]
looking forward to it
11am PST

**Comment by wanderer** [comment]
ok report back from the meeting. participants where @kumavis @tcoulter @frankiebee @axic @flyswatter @SilentCicero I think the general sentiment was to merge ethjs and ethereumjs. 
There are some conflicting libs that need to be sorted out 

- https://github.com/ethereumjs/ethereumjs-abi
- https://github.com/ethereumjs/ethereumjs-wallet
- https://github.com/ethereumjs/ethereumjs-units
- https://github.com/ethereumjs/ethereumjs-icap

Other action items
- there are several that deprecated libs that need to go.
- we need a shine website, that categorizes the modules and host other docs 
- coms channels should be shared

Anything else?

**Comment by kumavis** [comment]
I'd like to do a weekly meeting with a 30min timecap
We went for 2 hours and there's a number of relevant things we didn't cover
* upcomming ethereumjs + ipfs hackathon in Seattle 02/05/2017 - 02/12/2017 [see here](https://github.com/ipfs/community/issues/188#issuecomment-270803377)
* ipfs-ethereum integration
* ipfs-backed light client
* ewasm roadmap

**Comment by flyswatter** [comment]
The link that I'd recommend first to someone reviewing this meeting is https://github.com/ethjs/docs

It's like the table of contents of ethjs, which is very nice.

**Comment by kumavis** [comment]
Next call: https://github.com/ethereumjs/organization/issues/6
