### ISSUE TITLE
The async library

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/organization#55]
This another meta-issue on how to improve IMO the state of ethereumjs in general.

Most libraries use the npm package [`async`](https://www.npmjs.com/package/async). This was kind of standard practice in the node.js community many years ago, but that's no longer the case.

Code written with this library is hard to read and maintain, and I believe it prevents new people from collaborating. Take a look at [this function](https://github.com/ethereumjs/ethereumjs-blockchain/blob/35fefe686e87b1e19192de9eaabb6229cff7cbe6/src/index.ts#L369-L536) for a clear example of how scary it can get.

Personal preferences apart, this library prevents v8 from creating async stack traces. These were released (enabled by default) in node 12. For them to work, you have to stick to `async`/`await`. If you don't, this feature removes some internal (e.g. `process._tickcallback` calls) stack frames, leaving an almost empty (even emptier than before!) stack trace.

I know this is a huge change, but I believe it's important. 

I think a good way to start working on this can be migrating the tests from a library. For example, [ethereumjs-blockchain's test](https://github.com/ethereumjs/ethereumjs-blockchain/blob/master/test/index.ts).

**Comment by holgerd77** [comment]
@alcuadrado Sina already removed most (all?) usages of the `async` package during the VM refactoring, so getting to consensus here should be relatively straight-forward. This was mostly in the `runXXX.ts` execution files if you want to have a look for inspiration, see e.g. [runBlock.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runBlock.ts) vs [runBlock.js](https://github.com/ethereumjs/ethereumjs-vm/blob/fix-test-fork-name-case-handling/lib/runBlock.js) (a bit hard to compare since history broke along with the TypeScript changes, I just used an old branch with the js files for this to compare manually).

This sounds highly obvious to me with a huge structural win both on the readability and debuggability side, so I think taking some effort here is very much worth it.

**Comment by evertonfraga** [comment]
Just to keep this warm and help whoever wants to contribute here. Those are the remaining uses of the async lib:

| File | Code |
|----|------|
[blockchain/test/index.ts:33](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/test/index.ts#L33) | `async.parallel(`
[blockchain/test/index.ts:631](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/test/index.ts#L631) | `async.series(`
[blockchain/test/index.ts:683](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/test/index.ts#L683) | `async.series(`
[blockchain/test/index.ts:732](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/test/index.ts#L732) | `async.series(`
[blockchain/test/index.ts:793](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/test/index.ts#L793) | `async.series(`
[blockchain/test/index.ts:801](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/test/index.ts#L801) | `async.series(`
[blockchain/test/index.ts:837](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/test/index.ts#L837) | `async.series(`
[blockchain/test/index.ts:897](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/test/index.ts#L897) | `async.eachOfSeries(`
[blockchain/src/index.ts:260](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L260) | `async.waterfall(`
[blockchain/src/index.ts:392](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L392) | `async.eachSeries(`
[blockchain/src/index.ts:424](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L424) | `async.eachSeries(`
[blockchain/src/index.ts:471](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L471) | `async.series(`
[blockchain/src/index.ts:511](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L511) | `async.parallel(`
[blockchain/src/index.ts:594](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L594) | `async.parallel(`
[blockchain/src/index.ts:708](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L708) | `async.whilst(`
[blockchain/src/index.ts:915](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L915) | `async.series(`
[blockchain/src/index.ts:1047](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L1047) | `async.whilst(`
[blockchain/src/index.ts:1057](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/blockchain/src/index.ts#L1057) | `async.series([getBlock, runFunc), function(err?: any) {`
[vm/tests/util.js:44](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/util.js#L44) | `async.mapSeries(`
[vm/tests/util.js:129](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/util.js#L129) | `var q = async.queue(function(task, cb2) {`
[vm/tests/util.js:371](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/util.js#L371) | `async.eachSeries(`
[vm/tests/util.js:384](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/util.js#L384) | `async.series(`
[vm/tests/util.js:389](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/util.js#L389) | `async.forEachSeries(`
[vm/tests/BlockchainTestsRunner.js:53](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/BlockchainTestsRunner.js#L53) | `async.series([`
[vm/tests/BlockchainTestsRunner.js:74](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/BlockchainTestsRunner.js#L74) | `async.eachSeries(testData.blocks, function (raw, cb) {`
[vm/tests/GeneralStateTestsRunner.js:49](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/GeneralStateTestsRunner.js#L49) | `async.series([`
[vm/tests/GeneralStateTestsRunner.js:115](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/GeneralStateTestsRunner.js#L115) | `async.series([`
[vm/tests/GeneralStateTestsRunner.js:151](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/GeneralStateTestsRunner.js#L151) | `async.eachSeries(testCases,`
[vm/tests/VMTestsRunner.js:14](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/tests/VMTestsRunner.js#L14) | `async.series([`
[vm/lib/runBlockchain.ts:26](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/vm/lib/runBlockchain.ts#L26) | `async.series([getStartingState, runBlock), cb)`

**Comment by holgerd77** [comment]
The merkle tree library is also a heavy `async` user, see e.g. [here](https://github.com/ethereumjs/merkle-patricia-tree/search?q=async&unscoped_q=async).

**Comment by holgerd77** [comment]
Not sure if there are still occurrences here, will keep this open.
