### ISSUE TITLE
Ethereumjs call 2

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/organization#6]
Forking this comment.
https://github.com/ethereumjs/organization/issues/5#issuecomment-270831299

Time: would the 12 or 13th work for everyone? 
Agenda Times: 
- upcomming ethereumjs + ipfs hackathon in Seattle 02/05/2017 - 02/12/2017 see here
- ipfs-ethereum integration
- ipfs-backed light client
- ewasm roadmap
- add more below

 @kumavis @tcoulter @frankiebee @axic @flyswatter @SilentCicero  @fanatid @tinybike 

meeting notes https://hackmd.io/EwBgzCxgHAjAtAFmLRTgHYT2gMwGwBG8+sAhtGLobMLsIkA

**Comment by wanderer** [comment]
@cdetrio

**Comment by tcoulter** [comment]
12th or 13th works for me.

**Comment by wanderer** [comment]
ok lets do the call on Friday the 13th at 13:13 EST, 10:13 PST, 18:13 UTC. Does this work for yall?

**Comment by tcoulter** [comment]
If possible, can someone organizing send out calendar invites?

**Comment by wanderer** [comment]
hangouts link: https://hangouts.google.com/call/qufnz6eta5dvna7x2t357usw7ue

**Comment by kumavis** [comment]
doot doot doot 🎉

**Comment by kumavis** [comment]
@wanderer please setup the next call, same-ish time, same-ish place 👍

**Comment by kumavis** [comment]
meeting notes https://hackmd.io/EwBgzCxgHAjAtAFmLRTgHYT2gMwGwBG8+sAhtGLobMLsIkA

**Comment by wanderer** [comment]
> @wanderer please setup the next call, same-ish time, same-ish place :+1:

this need to be automated

**Comment by wanderer** [comment]
move to here https://github.com/ethereumjs/organization/issues/7
