### ISSUE TITLE
Point to discord instead of gitter

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/organization#62]
Our repo's currently point to gitter instead of discord. Let's change that.

**Comment by ryanio** [comment]
sounds good! I already created a badge if everyone likes it:

[![Discord][discord-badge]][discord-link]

[discord-badge]: https://img.shields.io/static/v1?logo=discord&label=discord&message=Join&color=blue
[discord-link]: https://discord.gg/TNwARpR

```
[![Discord][discord-badge]][discord-link]

[discord-badge]: https://img.shields.io/static/v1?logo=discord&label=discord&message=Join&color=blue
[discord-link]: https://discord.gg/TNwARpR
```

**Comment by holgerd77** [comment]
Yes, makes sense, Discord badge looks also nice. 👍

**Comment by evertonfraga** [comment]
My criteria was: every non-archived project that had commits >=2019 and had a gitter badge.

There are about 3 projects that do not have any sort of chat badge, I can add to them later.  

https://github.com/ethereumjs/ethereumjs-abi/pull/85
https://github.com/ethereumjs/organization/pull/65
https://github.com/ethereumjs/ethashjs/pull/28
https://github.com/ethereumjs/ethereumjs-wallet/pull/134
https://github.com/ethereumjs/ethereumjs.github.io/pull/8
https://github.com/ethereumjs/ethereumjs.github.io/pull/7
https://github.com/ethereumjs/ethereumjs-testing/pu
https://github.com/ethereumjs/ethereumjs-client/pull/141ll/50
https://github.com/ethereumjs/ethereumjs-client/pull/141
https://github.com/ethereumjs/ethereumjs-util/pull/273
https://github.com/ethereumjs/ethereumjs-util/pull/273
https://github.com/ethereumjs/ethereumjs-vm/pull/854

**Comment by holgerd77** [comment]
This has been addressed (at least for the very most part, not sure if there are 1-2 occurrences left, but these can be done on occasion).

Will close.
