### ISSUE TITLE
Performance Improvements Strategy & Tracking Issue

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/organization#64]
This issue is to keep track of the ongoing activities around improving the performance of the various EthereumJS libraries - especially the VM - and serve as a general entry point to the topic.

# Focus

## Improvement Targets

The following library parts are especially suited for performance improvement work (feel free to add):

Library | Improvement Ideas | Tracking Issue
--- | --- | ---
[VM](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/vm/lib) | Execution, Cache Improvements (StateManager), Stack & Memory Management, Precompiles | https://github.com/ethereumjs/ethereumjs-vm/issues/865
[Merkle Patricia Tree](https://github.com/ethereumjs/merkle-patricia-tree/tree/master/src) | Checkpointing, Storage Backend, Tree Search, Cache Improvements (Tree Search, Storage) | https://github.com/ethereumjs/merkle-patricia-tree/issues/132
[Ethash](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/ethash/src) | Overall Execution |
[Util](https://github.com/ethereumjs/ethereumjs-util/tree/master/src) | Hashing, Signatures |
[RLP](https://github.com/ethereumjs/rlp) | Encoding / decoding, highly used in e.g. MPT |

## Improvement Areas

Possible improvements areas:

- Algorithmic Improvements on performance sensitive code parts (iteration strategy, data structures,...)
- More sophisticated caching
  - Cache Structure & Setup (what to store? how long to store? where to store?)
  - Cache Application (when to use? when to flush?)
- Storage Backends
- Build Improvements (build target, dependencies, compiler flags,...)
- Environment & Language (WASM)

# Benchmarks / Tooling

## Performance Measurement Setups

Helpful setups for performance analysis:

- Dedicated benchmarking tool
- CI Runs
- Behaviour (optimally on reproducible tasks) in a productive environment (e.g. the VM within [Buidler](https://github.com/nomiclabs/buidler))

## Benchmark Tooling

Helpful JavaScript/CI Tooling:

- [Benchmark.js](https://benchmarkjs.com/): benchmarking library
- [github-actions-benchmark](https://github.com/rhysd/github-action-benchmark): GitHub Action for CI

# Progress Tracking

It would be nice if we collect some comprehensive results on progress being made over time here.

Note: this can be challenging if the benchmarking suite evolves/changes significantly over time. We'll see.

**Comment by s1na** [comment]
Great initiative!

On the VM side, I'd like to add investigating the performance penalty of the `AsyncEventEmitter`, I think it's draining a lot of time. Something else we discussed was how MPT doesn't clear the db nodes after the trie changes.
