### ISSUE TITLE
Ethereumjs call 3

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/organization#7]
Call Friday 20th at 13:13 EST, 10:13 PST, 18:13 UTC. 

@kumavis @tcoulter @frankiebee @axic @flyswatter @SilentCicero @fanatid @tinybike @cdetrio

Last meeting notes https://hackmd.io/EwBgzCxgHAjAtAFmLRTgHYT2gMwGwBG8+sAhtGLobMLsIkA
Last meeting's issue https://github.com/ethereumjs/organization/issues/6

Agenda
* review progress on ewasm
* ipld interop progress
* ???

**Comment by romanman** [comment]
@wanderer : where can I sync with your work on ewasm?

**Comment by wanderer** [comment]
@romanman yes of course! How can I get ahold of you?

**Comment by romanman** [comment]
@wanderer : I am very easy to find, I think there is no slack channel 
I am not logged in. But can't find you on skype anymore :(
