### ISSUE TITLE
Rename organization

### ISSUE THREAD

**Issue by TimDaub** [ethereumjs/organization#72]
When looking for JavaScript libraries that can be used within Ethereum, I often end up on this organization or one of its repos. For most of the time, however, I end up being confused as the code is "ts" and not "js".

Even for the main repo that is called "https://github.com/ethereumjs/ethereumjs-monorepo", 98% of the code is Typescript and not Javascript. Hence, to label appropriately what is contained in the repositories, I'd like to suggest that you rename or anyways distinguish repositories or your organization.

"Ethereum Javascript Community - Your Javascript Gateway to Ethereum". could become

"Ethereum Typescript Community - Your Typescript Gateway to Ethereum"

I'm aware that this issue description may sound controversial. Do I want to start a flamewar? No. Rather, I see it as a bureaucratic and proper thing to label a repository by what it contains. That's all.

**Comment by holgerd77** [comment]
Hi Tim,
the libraries we provide are explicitly meant to be used with JavaScript, on distribution we transpile them to either ES5-compliant JS (for the browser) respective ES 2017 JS (for Node). So the libraries are targeted to be used both by JavaScript and TypeScript projects, so our own step towards TypeScript was not meant to go away from the JS community but rather as an expansion to allow for supporting both worlds.

If you have got problems using the libraries in a JS environment let us know.

**Comment by TimDaub** [comment]
I understand that the intention is good. But personally, I'm hesitant to use any Typescript Ethereum library in any of my JavaScript projects:

- I don't know how to write TS; I don't want to include a library in my project that I'm potentially not capable of maintaining with my current knowledge
- From what I understand, TS is not standardized within TC39. It's a product by Microsoft. I'm not interested in using this particular product of Microsoft. I'd prefer to base my code on a standard
- It's unclear to me if TS will stay close to the JS language trunk or if it'll start diverging in the future
- The tooling for TS is different from JS

There are indeed also practical problems from exporting TS into ES5. I've reported them:

- https://github.com/ethereumjs/ethereumjs-monorepo/issues/978

Regarding the argument about using TS to cater to JS: I understand that you frame it as an approach towards catering to the JS community. But as a member of the JS community, I can say for myself that it is not helpful. It'd rather have the incentives such that you write JS code and have to *deal with it*, as otherwise, problems like the one in the above-linked issue arise. Another option is of course to label the org and its repos according to what they contain: Typescript.
