### ISSUE TITLE
Weekly Ethereumjs Meeting

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/organization#8]
@kumavis @tcoulter @frankiebee @axic @flyswatter @SilentCicero @fanatid @tinybike @cdetrio

meeting notes https://hackmd.io/EwBgzCxgHAjAtAFmLRTgHYT2gMwGwBG8+sAhtGLobMLsIkA

time 3:00 EST, 10:00 PST, 17:00 UTC on Fridays. 

ALL; [here is the ICS event](http://localhost:8080/ipfs/QmYh3xLT8du1cVdCPHRgeBGTKpMUvwkkZjECLNuDPCBM7G), make sure to save with a '.ics' and then import into calendar software

**Comment by wanderer** [comment]
https://plus.google.com/hangouts/_/calendar/dGhlbmlja2RvZHNvbkBnbWFpbC5jb20.m37a8o7jhikbar1jp303neqcl0?authuser=0

**Comment by wanderer** [comment]
meeting notes for 3/3/17 https://hackmd.io/IwYwHCBMIIZgtAUwCwDMDM9kFZIAZ4BOMRReEU9Q1YAIwoDYATIA

**Comment by wanderer** [comment]
meeting notes https://hackmd.io/MwTg7AJghgDAHDAtBMBGAxogLC1ioBmAbHIgKxkBG6ATHFKgQamUA===

**Comment by SilentCicero** [comment]
3 EST on Fridays works for me.
