### ISSUE TITLE
Hackathon Date/Place?

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/organization#9]
Cast your votes for the time and place of the next Ethereum JS (and related projects ... looking at you ipfs :P) Hackathon! Let's hear where you want to go. 

Last time was in Seattle, US so lets try to hit a different country and
@SilentCicero  wanted to go somewhere warm

**Comment by frankiebee** [comment]
@axic 
@flyswatter 
@kumavis 
@zandy

**Comment by wanderer** [comment]
@frozeman @aakilfernandes @fanatid @diasdavid

**Comment by tinybike** [comment]
Do I get a vote?  If so, I vote for Taipei, Taiwan, sometime in the next couple months!  Late April maybe?  (Note: my vote for Taipei is only valid for non-summer months...)

**Comment by tinybike** [comment]
(If a summer timeline is more realistic, then I vote for Cape Town, South Africa.)

**Comment by diasdavid** [comment]
Where is everyone located? It would make sense to pick a place that optimizes for flight time if are going to be there just for a week. Summer is coming and southern Europe is getting a lot warmer :)

**Comment by axic** [comment]
I suggest some remote villa in Portugal or Spain 😉

**Comment by wanderer** [comment]
@axic can you drop in a link to that one villa in Spain you should me on facebook?

**Comment by wanderer** [comment]
> Where is everyone located? 

@flyswatter
@kumavis
@frankiebee 

are west coast

@frozeman 
@axic 
@fanatid 

are all European i think

**Comment by flyswatter** [comment]
We just did a west coast one, I guess I could be convinced to visit some villa in Spain :)

**Comment by fanatid** [comment]
do you already know dates for hackathon?

**Comment by diasdavid** [comment]
I've heard good things about this Surf Mansion http://www.jangasurfmansion.com/mansion.html lot's of rooms, pool, snooker and surf lessons with gear included :) Around 50 € a night per person.

**Comment by wanderer** [comment]
@fanatid not yet, that is what this issue is for, let us know what dates would work for you :)

**Comment by axic** [comment]
@wanderer the one I've been to is https://www.facebook.com/calvisodegaia/

The family running it is super nice, one of them is a chef and is happy to provide meals made on site 😉

**Comment by frankiebee** [comment]
@tinybike what summer are you speaking of? the summer in the US or summer in Cape town? 
Because Cape Town, South Africa in July seems too look pretty cold

**Comment by apmilen** [comment]
@frankiebee you mean Zug Switzerland?

**Comment by frankiebee** [comment]
Maybe it would be cool to do right after devcon3, as far as time line stuffs...

**Comment by jpitts** [comment]
Taipei is a great place if the gathering is planned for Asia: inexpensive, convenient, and lots of English is actually spoken there. Summer is hottt though. Been there a bunch of times.

**Comment by kumavis** [comment]
IPFS team meet in april

**Comment by frankiebee** [comment]
@pipermerriam vote here

**Comment by pipermerriam** [comment]
I'd like to toss Boulder CO into the mix.

**Comment by Sulejman** [comment]
What do you think can it be made for remote teams too?

**Comment by wanderer** [comment]
@Sulejman we had remote team last time and I'm sure that it will be fine this time too, but in person is always better :)

**Comment by jpitts** [comment]
Bahamas sounds good because this would make it easier for European participants this time around.

But is the Bahamas expensive? If it is too expensive, EthereumJS could meet in South Florida one week before or after, and those with the budget could then bounce over to the IPFS gathering.

**Comment by bneiluj** [comment]
@wanderer Let's make it in Europe - we have the biggest ethereum / crypto community. 
Paris / London

**Comment by Sulejman** [comment]
@wanderer thanks for info 👍

**Comment by frankiebee** [comment]
Okay so looks like we've got a couple people wanting Spain. So lets Do that now we need to pick dates.

**Comment by frankiebee** [comment]
What a good time of the year for @all

**Comment by diasdavid** [comment]
Hi y'all, any updates on here? Need to make sure I don't schedule something on the same dates :)

**Comment by frankiebee** [comment]
@diasdavid spain fell through and we just decided to do Hawaii are you still interested?

**Comment by axic** [comment]
@diasdavid if you know a good place in Portugal to do it we may be able to convince the folks to come over 😉

**Comment by bneiluj** [comment]
Cascais in Portugal is really good. 
Or 
Around Bordeaux / Biscarrosse in France (Best wine, food and great weather 🤗).

**Comment by frankiebee** [comment]
I do want to have something booked by the end of this week though so we can get plain tickets

**Comment by frankiebee** [comment]
@apmilen cant do Hawaii either so he may want to chime in on Portugal

**Comment by frankiebee** [comment]
okay @axic @diasdavid @whyrusleeping MetaMask devs are indifferent to the location(havent herd from @kumavis on it though). it would be grat to get a sold head count however to make it easy to get a house

**Comment by diasdavid** [comment]
@axic a good place, what about the WHOLE country? :D

### Porto
![image](https://user-images.githubusercontent.com/1211152/27432969-6ef6f38a-574a-11e7-8780-11f0dbd7884a.png)

### Cascais
![image](https://user-images.githubusercontent.com/1211152/27432998-8ecf6c00-574a-11e7-9476-ffa0532bbf87.png)

### Lisbon
![image](https://user-images.githubusercontent.com/1211152/27433062-da88d5b4-574a-11e7-817e-41df9032e8b8.png)

It's going to be really hot in July though, we will need a place to hack with AC. Make sure to check that as a Airbnb feature, Portugal missed the note about house insulation and AC and most houses still don't have it.

There is a growing Blockchain community here too https://www.meetup.com/blockchainpt/ 

There are more places that would be great for this kind of trip (i.e Sesimbra, Peniche, Ericeira) but they would require us to rent cars.

**Comment by diasdavid** [comment]
That being said, I really need to know dates for this one asap. 

I'm also really down to Hawaii, never been :)

**Comment by axic** [comment]
@diasdavid I'm actually flying tomorrow to Lisbon (and next week a day trip to Porto) 😉

**Comment by diasdavid** [comment]
woot! @axic how long are you staying? let's meet up! Mail me!

**Comment by frankiebee** [comment]
Sorry to do this guys but @kumavis feels that this is a little rushed now and @flyswatter agreed so i think were going to have to back out. I know we hot you guys all excited I'm sorry 😞
